services:
  - type: web
    name: kong-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        value: YOUR_DISCORD_BOT_TOKEN_HERE
    ports:
      - port: 10000
        protocol: tcp
